USE [master]
GO

/****** Object:  Database [WBank of America]    Script Date: 10/28/2015 11:47:48 AM ******/
CREATE DATABASE [WBank of America]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WBank of America', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WBank of America.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WBank of America_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\WBank of America_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WBank of America] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WBank of America].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WBank of America] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WBank of America] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WBank of America] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WBank of America] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WBank of America] SET ARITHABORT OFF 
GO

ALTER DATABASE [WBank of America] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WBank of America] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WBank of America] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WBank of America] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WBank of America] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WBank of America] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WBank of America] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WBank of America] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WBank of America] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WBank of America] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WBank of America] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WBank of America] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WBank of America] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WBank of America] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WBank of America] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WBank of America] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WBank of America] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WBank of America] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WBank of America] SET  MULTI_USER 
GO

ALTER DATABASE [WBank of America] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WBank of America] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WBank of America] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WBank of America] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WBank of America] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WBank of America] SET  READ_WRITE 
GO


